yoshiharuyamashita/blackburn

layouts/_default/li.html
layouts/partials/post_meta.html

To avoid numerous template error messages when the end user does not define [params] dateFormat in config.toml

Add fallback for dateFormat

---

layouts/partials/social.html

Howdy,
I noticed that some logos were square and some were not.  Font Awesome provides square versions of almost all of the logos that are otherwise not square, and switching to them helps provide a unified appearance for the social logos.  So that's one of the changes within.  The other change was to add an entry for Hacker News.
Thanks.

Add additional social item for Hacker News and unify logo appearance

---

layouts/partials/prev_next_post.html

These were introduced in Hugo 0.12.0
This fixes an issue I was seeing where the 'next' page for a post was the top level 'about' page

Update prev_next_post template to use .NextInSection and .PrevInSection

---

layouts/index.html

If you have pages that aren't the post type, the pagination would cause empty index pages.
To reproduce:
* Create a lot (10+) of pages that aren't "post" type
* Create a post
* Load the index page, and note that the pagination has more than 1 page, but only 1 post

Fix a bug where the index would have empty pages

---

layouts/partials/head.html
layouts/partials/social.html

Previously it was possible to create a nonexist link. If `Site.BaseURL` didn't end in a `/` the
constructed RSS link would be of the form `http://mysite.comindex.xml`
See https://gohugo.io/templates/rss/ for details on `RSSLink`

Use .RSSlink rather than manually building link

---

layouts/partials/social.html

[Keybase.io](https://keybase.io/) is a social proof service which allows users to ease the burden of PGP.  It uses the online social accounts + signed proofs as a basis for identity verification and provides high-performance tooling written in Go to interact with PGP and NaCL for sending and receiving encrypted messages from users, certifying ownership of devices, tracking users, and transferring encrypted files with KBFS.  It also acts as a central public place where you can provide cross-verified ownership of your social media accounts.
Currently Keybase.io does not have an icon in Font Awesome, so the fairly standard use case now is to substitute `fa-key` which is what I've done here.
[My Keybase profile](https://keybase.io/tristor) can serve as an example for what someone might link …

Add social icon for Keybase.io

---

layouts/partials/social.html

GNUSocial is similar to Twitter, but an open-source project. The thing is, that users could very well be on different instances than the one I've listed. I am open to ideas on how to solve it.
As for the icon, Font Awesome does not have a GNUSocial icon, so I'm using the `fa-comment` icon instead, in line with @Tristor 's work on Keybase.

Adding GNUSocial as a social item in sidebar

---

layouts/partials/head.html
layouts/partials/social.html

The former will be deprecated and eventually removed from Hugo.
Note: Currently both of them exist in Hugo, which is the reason for the cleanup.

Rename RSSlink to RSSLink

---

layouts/partials/social.html

MobyGames is a database of game developers, so this social link might be useful to game developers using the Blackburn theme.

Add MobyGames to social links (gaming)

---

layouts/partials/sidemenu.html

Allow for xdg style links like bitcoin: or irc: in the
sidemenu.html file.

Per issue #49 safeHTMLAttr

---

archetypes/default.md

Hugo 0.24 onward require the date and title to be provided in the archetype so I used some sane defaults.

Fix archetype missing date and title warning

---

archetypes/default.md

fixed following error:
```
vagrant@vagrant-ubuntu-trusty-64:~/myblog$ hugo new post/test2.md
/home/vagrant/myblog/content/post/test2.md created
vagrant@vagrant-ubuntu-trusty-64:~/myblog$ hugo undraft content/post/test2.md
panic: interface conversion: interface {} is time.Time, not string
goroutine 1 [running]:
github.com/gohugoio/hugo/commands.undraftContent(0xf59420, 0xc420043580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/Users/bep/go/src/github.com/gohugoio/hugo/commands/undraft.go:111 +0xad7
github.com/gohugoio/hugo/commands.Undraft(0xfa7700, 0xc420012b50, 0x1, 0x1, 0x0, 0x0)
/Users/bep/go/src/github.com/gohugoio/hugo/commands/undraft.go:63 +0x1b5
github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).execute(0xfa7700, 0xc420012ad0, 0x1, 0x1, 0xfa7700, 0xc420012ad0) …
```

Fix archetype generating date is not string type

---

README.md

The markdown in the README file had a formatting issue because of which the text `Pure CSS` was not displayed as the label for the URL. This PR fixes that issue.

Fixed the formatting of URL to PureCSS #

---

README.md
layouts/shortcodes/pure_table.html

Example usage at the bottom of this post:
http://charlesjlee.com/post/20170108-steem-bot/
```
{{<pure_table
"key|example value|comment"
"numPostsToConsider|20|Number of recent posts to consider"
"percentChanceToPost|5|Percent chance that script will run. Must be between 0 and 100"
"steemAccountName|'mySteemName'|Your Steem account name wrapped in single quotes"
"steemPostingKey|'myPrivatePostingKey'|Your Private Posting Key that you saved when creating your SteemIt account, wrapped in single quotes"
"voteWeight|100|How much voting power to use per upvote. Note that voting power decreases after every vote. Must be between 0 and 100"
>}}
```

New shortcode "pure_table" to create tables

---

README.md
layouts/partials/head.html

Allow params.custom_css and params.custom_js to contain HTTP and HTTPS
URLs.

Allow external JS and CSS to be included

---

layouts/partials/google_analytics.html

Disable google analytics when working from localhost. There is precedent for this in [`disqus.html`](https://github.com/yoshiharuyamashita/blackburn/blob/1bd3b1a49e8bc7f1236377fb8d65d947fc6f8af7/layouts/partials/disqus.html#L8). Without this change, traffic will be reported to google, which is inaccurate, and can mess up stats by counting local traffic.
You can see this in action on my [blog](https://blog.jamesotten.com/).

Disable google analytics on localhost

---

layouts/partials/prev_next_post.html

Using command "hugo server" with v0.51 gives the following messages:
WARNING: Page's .Prev is deprecated and will be removed in a future release. Use .NextPage (yes, not .PrevPage).
WARNING: Page's .Next is deprecated and will be removed in a future release. Use .PrevPage (yes, not .NextPage).

Update deprecated Page variables: .Prev & .Next

---

layouts/partials/footer.html
layouts/partials/sidemenu.html
static/css/blackburn.css
static/js/menus.js

Sub-menu was not working as expected. Changes below has been made:
1. Add `.pure-menu-link` to children menus for layout uniformity
2. `overflow-y` removed from `#menu` so submenu can show up without scrolling the menu horizontally to see submenu
3. `#menu a` to have right padding restored for submenu link layout
4. Remove top border of `ul` for submenus
5. Add JavaScript as [recommended by PureCSS](https://purecss.io/menus/#dropdowns) - [example script](https://purecss.io/js/menus.js)
Closes #74

Fix expansion of submenu

---

archetypes/default.md

Starting with v0.35 TranslationBaseName was replaced for Name on the archetype template. 
See https://github.com/gohugoio/hugo/commit/863a812e07193541b42732b0e227f3d320433f01

hugo v0.35 modified archetype value

---

layouts/partials/social.html

[rel="me"](https://indieweb.org/rel-me) is a commonly used way to show that that two websites or social media accounts are the same, and is used for authentication and proving site ownership in a variety of ways.

Adds rel-me to social links

---

layouts/index.html

Using only .Data.Pages will only show a link to the Post page in the home page. Using .Site.RegularPages returns the homepage to a normal showcase of existing posts. This change happened starting at Hugo >0.57.

Remove .Data.Pages in favor of .Site.RegularPages

---

layouts/partials/head.html

Hey, I needed this functionality, and it might be a good addition to your codebase as well.
I need to publish my content, but I'm also obliged to point to canonical version of it (on third party blog that actually paid me to write it). So now I can

Add canonical header link from content preamble

---

layouts/partials/footer.html
layouts/partials/footer_mathjax.html

I had to add the mathjax partials to the theme when I pulled it for my Hugo blog. It looked like the partial`footer_mathjax.html` and the partial reference in `footer.html` were missing. Once I added those to my local copy of Blackburn, I had mathjax capabilities immediately. Thought I'd make a PR just so they're updated for whoever comes next.

Add mathjax partials (and capabilities) to Blackburn theme.

---

layouts/_default/taxonomy.html

Without the default, taxonomies like "categories" or "authors" don't render their lists of items.
I copied the taxonomy/tag.html template. I think the tag & topic taxonomy templates can be deleted, if you want.
[Docs](https://gohugo.io/templates/list/#taxonomy-lists)

Add a default taxonomy list template

---

layouts/partials/commento.html
layouts/post/single.html

It's been quite some time since I worked on my website, but I started back up recently and I am concerned that this theme may be unmaintained since it has several pending PRs.  That said, I am going to open a few today to add some things I think are useful, this is the first.
Inspired by the recent thread on [HackerNews](https://news.ycombinator.com/item?id=26033052) about the misbehavior of Disqus I updated my website to use Commento.io instead as noted in my recent [post](https://tristor.ro/blog/2021/02/05/replacing-disqus-with-commento.io/).  There are other Disqus alternatives in market that are privacy respecting, including [Isso](https://posativ.org/isso/), but I chose Commento.io for a few different reasons.
Disqus unfortunately got acquired by an ad-tech company and they now use …

Add support for Commento.io as a Disqus alternative.

---

layouts/partials/footer_mathjax.html

This patch you may not want to accept, but I'm submitting the PR to make it simple for others to take the patch if they wish in their own forks.  The reasoning is that I've removed what was previously a configurable set of parameters with some fallback logic to instead make a hardcoded decision that closely matches the prior default.
The sum total of this change is that it does the following:
1. Removes parameterization logic
2. Uses CloudFlare's CDNJS (which is recommended by the MathJax project) instead of cdn.bootcss.com, which was hanging infinitely for me on my site
3. Bumps the specific version requested from the previous 2.7.1 to 2.7.7, which is the last release in the 2.7 series and I confirmed didn't seem to break anything in my testing.

Use CDNJS for MathJax instead of cdn.bootcss.com

---

layouts/partials/footer.html
layouts/partials/goatcounter_analytics.html

Following up on my changes in PR #106, I was also looking for alternatives to the default of Google Analytics.  I don't think I need to explain why Google Analytics isn't the best option from a privacy perspective or a page weight perspective.
There are numerous options out there, some of which I considered specifically which included [Plausible](https://plausible.io/), [Offen](https://www.offen.dev/), and obviously [GoatCounter](https://www.goatcounter.com/).  The big selling point for GoatCounter over other privacy-respecting alternatives is that it's a SaaS which has a free tier for NON-COMMERCIAL use.  This means folks who are hosting Hugo sites with this theme in places where they cannot deploy other services can still get analytics.  This was one motivator for why I picked Commento …

Adding in support for GoatCounter privacy respecting analytics.

---

layouts/partials/share.html

While fixing PR #106, I found that the Twitter share button built-in to this theme is appending a `via=` block which references the Twitter user @HorribleGeek. I'm guessing they may have contributed the original change to the theme and it missed being cleaned up.  This PR fixes this.

Remove appended via= block from Twitter share button

---

layouts/partials/social.html

In `layouts/partials/social.html` there are a few icons missing the `fa-fw` class value, which are interestingly the only icons misaligned.  From the [Font Awesome docs](https://fontawesome.com/v4.7.0/examples/) this sets the icons to a fixed width, which seems reasonable for the sidebar.  This patch fixes the following icons to also have this set, and causes all icons to align on my system.
Icons affected:
* LinkedIn
* RSS
* GNU Social
* MobyGames
* BitBucket
* Keybase

Adds the fa-fw class to the some social icons missing this class.

---

layouts/partials/share.html

This is a resubmission of PR #101 by @tetsuyainfra, rebased onto current master.  This fixes the issue reported in #104, which is caused by Font Awesome requiring an additional class to be applied since Font Awesome 5.
My fix in #107 included a fix for the Twitter icon, but not the rest, which I didn't realize when I cherry-picked it.  So when I test against current master without this change, only the Twitter share button shows up.

modify SNS share button at layouts/partials/share.html

---

layouts/_default/section.html

I am not certain exactly when the change was made in Hugo, but I think it was sometime around 0.55 release.  This just adds the default section template from [the Hugo documentation](https://gohugo.io/templates/section-templates/) into the theme, which does not appear to break anything on my site.  This eliminates the [warning message](https://discourse.gohugo.io/t/found-no-layout-file-for-html/18983) that currently happens every time you build your site using blackburn.

Add the recommended default section template into layouts/_default

---

layouts/partials/head.html

Howdy,
One of the things I've been improving lately on my site is the performance.  Many of the earlier changes were driven by that desire, and this is another small change that has helped performance.  I'm down to under 400ms for a full paint on desktop and under 800ms on mobile in my testing once making this change.
This change does three things:
1. Preferences using the CloudFlare provided CDNJS for externally loaded assets
2. Uses the latest version of FontAwesome 5 with minified CSS
3. Asynchronously loads MathJax and HighlightJS
Thanks

Performance improvements by asynchronous loading of optional JS extensions in the header
